// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLkgG0yjbBJKBcdfXKoKNs-snxmeXv58E',
    appId: '1:337888451348:web:fd63152a0977906ff5c001',
    messagingSenderId: '337888451348',
    projectId: 'idevio-app',
    authDomain: 'idevio-app.firebaseapp.com',
    storageBucket: 'idevio-app.firebasestorage.app',
    measurementId: 'G-M815DH651J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeco-b3qMHO5IpzM_BuJh2WZmhIGXP090',
    appId: '1:337888451348:android:40d993a0d4560459f5c001',
    messagingSenderId: '337888451348',
    projectId: 'idevio-app',
    storageBucket: 'idevio-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOxnQjbiI58UOMrwtouWHRsydLMJ1CBdU',
    appId: '1:337888451348:ios:58d76e85a753e93df5c001',
    messagingSenderId: '337888451348',
    projectId: 'idevio-app',
    storageBucket: 'idevio-app.firebasestorage.app',
    iosBundleId: 'com.example.ideaGeneratorAppV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOxnQjbiI58UOMrwtouWHRsydLMJ1CBdU',
    appId: '1:337888451348:ios:58d76e85a753e93df5c001',
    messagingSenderId: '337888451348',
    projectId: 'idevio-app',
    storageBucket: 'idevio-app.firebasestorage.app',
    iosBundleId: 'com.example.ideaGeneratorAppV2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLkgG0yjbBJKBcdfXKoKNs-snxmeXv58E',
    appId: '1:337888451348:web:f51f89c647de09a1f5c001',
    messagingSenderId: '337888451348',
    projectId: 'idevio-app',
    authDomain: 'idevio-app.firebaseapp.com',
    storageBucket: 'idevio-app.firebasestorage.app',
    measurementId: 'G-LM7C46KWBN',
  );
}
